/**
 * 各職業故事、任務與專屬攻擊
 * 任務 kind：0 討伐魔物 · 1 通關關卡 · 2 擊敗首領 · 3 達到等級 · 4 使用技能
 */
(function (global) {
  global.HeroStories = {
    warrior: {
      name: "阿爾德里克",
      className: "戰士",
      title: "落堡之誓",
      intro:
        "騎士阿爾德里克獨守邊境堡壘。王都陷落後魔物湧入荒野，他是村莊前的最後防線。重劈與盾牆，是他僅剩的語言。",
      attackName: "重劈",
      attackDesc: "近戰：需貼近敵人（相鄰一格）",
      quests: [
        {
          title: "邊境巡邏",
          desc: "擊敗 10 隻魔物",
          kind: 0,
          target: 10,
          rewardExp: 22,
          rewardItems: [{ name: "藥草", qty: 2, heal: 12 }],
        },
        {
          title: "初陣試煉",
          desc: "通關第 1 關（擊敗首領）",
          kind: 1,
          target: 1,
          rewardExp: 35,
          rewardItems: [{ name: "治療藥水", qty: 1, heal: 35 }],
        },
        {
          title: "盾牆演練",
          desc: "使用技能 6 次",
          kind: 4,
          target: 6,
          rewardExp: 28,
          rewardItems: [{ name: "魔力藥水", qty: 1, heal: 0, mp: 30 }],
        },
        {
          title: "荒野清剿",
          desc: "擊敗 22 隻魔物",
          kind: 0,
          target: 22,
          rewardExp: 40,
          rewardItems: [{ name: "藥草", qty: 3, heal: 12 }],
        },
        {
          title: "首領獵殺",
          desc: "擊敗 2 隻首領",
          kind: 2,
          target: 2,
          rewardExp: 50,
          rewardItems: [{ name: "強效藥水", qty: 1, heal: 60 }],
        },
        {
          title: "雪原前哨",
          desc: "通關第 3 關",
          kind: 1,
          target: 3,
          rewardExp: 55,
          rewardItems: [{ name: "治療藥水", qty: 1, heal: 35 }],
        },
        {
          title: "鐵血誓言",
          desc: "達到 4 級",
          kind: 3,
          target: 4,
          rewardExp: 45,
          rewardItems: [{ name: "魔力藥水", qty: 1, heal: 0, mp: 30 }],
        },
        {
          title: "落堡奪還",
          desc: "通關全部 5 關",
          kind: 1,
          target: 5,
          rewardExp: 100,
          rewardItems: [{ name: "強效藥水", qty: 2, heal: 60 }],
        },
      ],
    },
    mage: {
      name: "萊拉",
      className: "法師",
      title: "破碎魔導書",
      intro:
        "大法師萊拉在災變中遺失了魔導書。殘存的咒文仍聽從她的召喚，但每一道火球都會引來更深的暗影。",
      attackName: "魔彈",
      attackDesc: "遠程：最遠 3 格，朝面向方向優先",
      quests: [
        {
          title: "魔彈試射",
          desc: "擊敗 10 隻魔物",
          kind: 0,
          target: 10,
          rewardExp: 22,
          rewardItems: [{ name: "乙醚", qty: 1, heal: 0, mp: 25 }],
        },
        {
          title: "凝聚精華",
          desc: "通關第 1 關",
          kind: 1,
          target: 1,
          rewardExp: 35,
          rewardItems: [{ name: "魔力藥水", qty: 1, heal: 0, mp: 30 }],
        },
        {
          title: "咒文鍛鍊",
          desc: "使用技能 8 次",
          kind: 4,
          target: 8,
          rewardExp: 32,
          rewardItems: [{ name: "乙醚", qty: 1, heal: 0, mp: 25 }],
        },
        {
          title: "精華狩獵",
          desc: "擊敗 24 隻魔物",
          kind: 0,
          target: 24,
          rewardExp: 42,
          rewardItems: [{ name: "藥草", qty: 2, heal: 12 }],
        },
        {
          title: "首領封印",
          desc: "擊敗 2 隻首領",
          kind: 2,
          target: 2,
          rewardExp: 52,
          rewardItems: [{ name: "治療藥水", qty: 1, heal: 35 }],
        },
        {
          title: "熔岩裂隙",
          desc: "通關第 3 關",
          kind: 1,
          target: 3,
          rewardExp: 55,
          rewardItems: [{ name: "乙醚", qty: 2, heal: 0, mp: 25 }],
        },
        {
          title: "大法師之證",
          desc: "達到 4 級",
          kind: 3,
          target: 4,
          rewardExp: 48,
          rewardItems: [{ name: "強效藥水", qty: 1, heal: 60 }],
        },
        {
          title: "封印終焉",
          desc: "通關全部 5 關",
          kind: 1,
          target: 5,
          rewardExp: 100,
          rewardItems: [{ name: "魔力藥水", qty: 2, heal: 0, mp: 30 }],
        },
      ],
    },
    priest: {
      name: "艾拉",
      className: "牧師",
      title: "最後聖所之歌",
      intro:
        "修女艾拉守護聖所最後一盞長明燈。治癒之光惹怒黑暗，她仍步入荒野，要把希望帶回岔路口。",
      attackName: "聖擊",
      attackDesc: "近戰：傷敵並小幅自癒",
      quests: [
        {
          title: "淨化魔物",
          desc: "擊敗 10 隻魔物",
          kind: 0,
          target: 10,
          rewardExp: 22,
          rewardItems: [{ name: "藥草", qty: 3, heal: 12 }],
        },
        {
          title: "淨化道路",
          desc: "通關第 1 關",
          kind: 1,
          target: 1,
          rewardExp: 35,
          rewardItems: [{ name: "治療藥水", qty: 1, heal: 35 }],
        },
        {
          title: "聖歌練習",
          desc: "使用技能 6 次",
          kind: 4,
          target: 6,
          rewardExp: 30,
          rewardItems: [{ name: "魔力藥水", qty: 1, heal: 0, mp: 30 }],
        },
        {
          title: "聖光巡禮",
          desc: "擊敗 20 隻魔物",
          kind: 0,
          target: 20,
          rewardExp: 38,
          rewardItems: [{ name: "藥草", qty: 2, heal: 12 }],
        },
        {
          title: "審判首領",
          desc: "擊敗 2 隻首領",
          kind: 2,
          target: 2,
          rewardExp: 50,
          rewardItems: [{ name: "治療藥水", qty: 2, heal: 35 }],
        },
        {
          title: "遺跡祈福",
          desc: "通關第 3 關",
          kind: 1,
          target: 3,
          rewardExp: 55,
          rewardItems: [{ name: "藥草", qty: 3, heal: 12 }],
        },
        {
          title: "聖者儀階",
          desc: "達到 4 級",
          kind: 3,
          target: 4,
          rewardExp: 45,
          rewardItems: [{ name: "強效藥水", qty: 1, heal: 60 }],
        },
        {
          title: "點亮神龕",
          desc: "通關全部 5 關",
          kind: 1,
          target: 5,
          rewardExp: 100,
          rewardItems: [{ name: "治療藥水", qty: 2, heal: 35 }, { name: "魔力藥水", qty: 1, heal: 0, mp: 30 }],
        },
      ],
    },
    thief: {
      name: "凱德",
      className: "盜賊",
      title: "王庫暗影",
      intro:
        "盜賊凱德為救妹妹竊走王冠寶石，卻喚醒庫中詛咒。森林裡的守衛不再放他無聲離去。",
      attackName: "暗襲",
      attackDesc: "近戰：高暴擊率",
      quests: [
        {
          title: "無聲狩獵",
          desc: "擊敗 10 隻魔物",
          kind: 0,
          target: 10,
          rewardExp: 22,
          rewardItems: [{ name: "藥草", qty: 2, heal: 12 }],
        },
        {
          title: "無聲腳步",
          desc: "通關第 1 關",
          kind: 1,
          target: 1,
          rewardExp: 35,
          rewardItems: [{ name: "乙醚", qty: 1, heal: 0, mp: 25 }],
        },
        {
          title: "暗殺演習",
          desc: "使用技能 8 次",
          kind: 4,
          target: 8,
          rewardExp: 30,
          rewardItems: [{ name: "魔力藥水", qty: 1, heal: 0, mp: 30 }],
        },
        {
          title: "影刃收割",
          desc: "擊敗 26 隻魔物",
          kind: 0,
          target: 26,
          rewardExp: 44,
          rewardItems: [{ name: "乙醚", qty: 1, heal: 0, mp: 25 }],
        },
        {
          title: "首領竊命",
          desc: "擊敗 2 隻首領",
          kind: 2,
          target: 2,
          rewardExp: 52,
          rewardItems: [{ name: "治療藥水", qty: 1, heal: 35 }],
        },
        {
          title: "深入遺跡",
          desc: "通關第 3 關",
          kind: 1,
          target: 3,
          rewardExp: 55,
          rewardItems: [{ name: "藥草", qty: 2, heal: 12 }],
        },
        {
          title: "夜影大師",
          desc: "達到 4 級",
          kind: 3,
          target: 4,
          rewardExp: 46,
          rewardItems: [{ name: "強效藥水", qty: 1, heal: 60 }],
        },
        {
          title: "破除詛咒",
          desc: "通關全部 5 關",
          kind: 1,
          target: 5,
          rewardExp: 100,
          rewardItems: [{ name: "乙醚", qty: 2, heal: 0, mp: 25 }, { name: "強效藥水", qty: 1, heal: 60 }],
        },
      ],
    },
  };

  global.JobCombat = {
    warrior: {
      basic: {
        name: "重劈",
        range: 1,
        rangeType: "melee",
        mpCost: 0,
        mult: 1.25,
        healSelf: 0,
        critPct: 0,
        ignoreDef: 0,
        fx: "slash",
        fxColor: "#c8d8ff",
      },
      skills: [
        {
          name: "衝鋒斬",
          key: "1",
          range: 2,
          rangeType: "dash",
          mpCost: 8,
          mult: 1.75,
          ignoreDef: 2,
          fx: "slash",
          fxColor: "#a0b8ff",
        },
        {
          name: "盾牆",
          key: "2",
          mpCost: 6,
          defBoostTurns: 3,
          fx: "buff",
          fxColor: "#88aaff",
        },
      ],
    },
    mage: {
      basic: {
        name: "魔彈",
        range: 3,
        rangeType: "ranged",
        mpCost: 0,
        mult: 0.95,
        ignoreDef: 1,
        fx: "bolt",
        fxColor: "#b8f0ff",
      },
      skills: [
        {
          name: "火球術",
          key: "1",
          range: 4,
          rangeType: "ranged",
          mpCost: 12,
          mult: 1.65,
          ignoreDef: 3,
          fx: "fireball",
          fxColor: "#ff8840",
        },
        {
          name: "冰霜環",
          key: "2",
          range: 2,
          rangeType: "ranged",
          mpCost: 16,
          mult: 1.15,
          aoe: true,
          fx: "frost",
          fxColor: "#88e8ff",
        },
      ],
    },
    priest: {
      basic: {
        name: "聖擊",
        range: 1,
        rangeType: "melee",
        mpCost: 0,
        mult: 0.95,
        healSelf: 6,
        fx: "holy",
        fxColor: "#ffe8a0",
      },
      skills: [
        {
          name: "治療術",
          key: "1",
          targetSelf: true,
          heal: 38,
          mpCost: 10,
          fx: "heal",
          fxColor: "#88ffaa",
        },
        {
          name: "審判光",
          key: "2",
          range: 3,
          rangeType: "ranged",
          mpCost: 14,
          mult: 1.55,
          ignoreDef: 2,
          fx: "holy",
          fxColor: "#fff0c0",
        },
      ],
    },
    thief: {
      basic: {
        name: "暗襲",
        range: 1,
        rangeType: "melee",
        mpCost: 0,
        mult: 1.05,
        critPct: 40,
        ignoreDef: 4,
        fx: "slash",
        fxColor: "#5ee8a8",
      },
      skills: [
        {
          name: "毒刃",
          key: "1",
          range: 1,
          rangeType: "melee",
          mpCost: 7,
          mult: 1.35,
          ignoreDef: 5,
          fx: "poison",
          fxColor: "#88ff60",
        },
        {
          name: "飛刀",
          key: "2",
          range: 3,
          rangeType: "ranged",
          mpCost: 5,
          mult: 1.2,
          critPct: 25,
          ignoreDef: 2,
          fx: "knife",
          fxColor: "#c0e8d0",
        },
      ],
    },
  };

  global.JobAttacks = {};
  for (const job of Object.keys(global.JobCombat)) {
    global.JobAttacks[job] = global.JobCombat[job].basic;
  }
})(typeof window !== "undefined" ? window : globalThis);
